### ISSUE TITLE
400 URL must be absolute, and question about session_id cooike

### ISSUE THREAD

**Issue by naftali100** [kaimi-ru/yandex-music-download#24]
A.
i get error 
[DEBUG] main::get_track_url(634): 
[DEBUG] main::get_track_url(637): Request failed
[DEBUG] main::log_response(1215): Response stored at log_1601474202

// log_1601474202
400 URL must be absolute
Content-Type: text/plain
Client-Date: Wed, 30 Sep 2020 13:56:42 GMT
Client-Warning: Internal response

400 URL must be absolute

i run: perl ya.pl -u https://music.yandex.com/users/yamusic-daily/playlists/121583123  --cookie "xxxxxx" --debug  --proxy xxxxxxxx
B.
i dont understand how to get the cooike session_id
i tried to copy-paste from chrom
![this what i copy](https://user-images.githubusercontent.com/48069590/94695700-e6cd4500-033e-11eb-8eb6-b003942a2e8b.png)
and i dont know how to put it in the arguments
so if you can explain how execly to do it
thanks

**Comment by kaimi-** [comment]
Hello,
400 URL is fixed in the current branch.

Cookie syntax should be as follows:
`perl ya.pl -u "https://music.yandex.com/users/yamusic-daily/playlists/121583123" --cookie "3:160.....z5pb_9sE1A"`
or
`perl ya.pl -u "https://music.yandex.com/users/yamusic-daily/playlists/121583123" --cookie "Session_id=3:160.....z5pb_9sE1A"`
either of these will work.
