### ISSUE TITLE
[ERROR] Can't get track list info!

### ISSUE THREAD

**Issue by mshibo** [kaimi-ru/yandex-music-download#3]
everytime i try to download anything with this script, i'm getting this error,

> E:>ya.pl -u https://music.yandex.ru/album/107020
> [INFO] Fetching album info: 107020
> 
> [ERROR] Can't get track list info

**Comment by kaimi-** [comment]
Run script with `--debug` option like this `ya.pl -u https://music.yandex.ru/album/107020 --debug`, it will create file named `log_****` in current directory, post file contents here.

Also, please:
1. Install Charles Web Proxy or Telerik Fiddler
2. Install Charles/Fiddler SSL root certificate in system CA trusted store (you can find manual on Charles/Fiddler web site or google it) and setup HTTPs traffic decryption in program settings
3. Run script
`ya.pl -u https://music.yandex.ru/album/107020`
also specify `--proxy 127.0.0.1:8888` (may vary) argument to tunnel script traffic through local proxy
4. Save and upload resulting log somewhere and post link here

It's probably due to some kind of redirects when using Yandex services from other countries.

**Comment by akaJedi** [comment]
Hey @kaimi- 
it seems like I have the same issue:

perl ya.pl --proxy 5.139.11.198:8279 -a 4439690
[INFO] Checking Yandex.Music availability
[OK] Yandex.Music is available
[INFO] Fetching album info: 4439690
[ERROR] Can't get track list info

with debug it looks like:

perl ya.pl --debug --proxy 5.139.11.198:8279 -a 4439690
[INFO] Checking Yandex.Music availability
[OK] Yandex.Music is available
[INFO] Fetching album info: 4439690
[DEBUG] main::create_json(948): Error decoding json , or ] expected while parsing array, at character offset 8 (before "(end of string)") at ya.pl line 943.

[DEBUG] main::get_album_tracks_info(586): Can't create json from data: , or ] expected while parsing array, at character offset 8 (before "(end of string)") at ya.pl line 943.

[DEBUG] main::log_response(1052): Response stored at log_1497296252
[ERROR] Can't get track list info

content of log file:

> HTTP/0.9 200 Assumed OK
> Client-Date: Mon, 12 Jun 2017 19:37:32 GMT
> Client-Peer: 5.139.11.198:8279
> Client-Response-Num: 1
> 
> [

**Comment by kaimi-** [comment]
@akaJedi 
Probably faulty proxy, response from the server seems to be incorrect. There is no problem with this album with properly working proxy.
